-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 22:19:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `element` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `is_agree` TINYINT NULL,
  `is_disagree` TINYINT NULL,
  `is_question` TINYINT NULL,
  `is_missing_source` TINYINT NULL,
  `is_link` TINYINT NULL,
  `is_emote` TINYINT NULL,
  `relevance` INT NULL,
  `parent_element_id` INT NULL,
  `brother_element_id` INT NULL,
  `debat_id` INT NOT NULL,
  `order` INT NULL,
  `logical_connector` VARCHAR(50) NULL,
  `emoticon` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `debat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `debat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
