-- MySQL Script generated by MySQL Workbench
-- Sun Jan 14 18:00:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `debats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `debats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  `author_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_debats_users1_idx` (`author_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `elements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `is_agree` TINYINT NULL,
  `is_disagree` TINYINT NULL,
  `is_question` TINYINT NULL,
  `is_missing_source` TINYINT NULL,
  `is_link` TINYINT NULL,
  `is_emote` TINYINT NULL,
  `relevance` INT NULL,
  `parent_element_id` INT NULL,
  `brother_element_id` INT NULL,
  `order` INT NULL,
  `logical_connector` VARCHAR(50) NULL,
  `emoticon` VARCHAR(50) NULL,
  `debat_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_elements_debats_idx` (`debat_id` ASC),
  INDEX `fk_elements_users1_idx` (`author_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
